name: Swift

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "2.8-CI-CD-Artem" ]
    
jobs:
  build:
  
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: brew install swiftgen
      - name: Build
        working-directory: 'App'
        run: xcodebuild -project TodoList.xcodeproj -scheme TodoList -destination 'platform=iOS Simulator,name=iPhone 13,OS=16.2'
      - name: Run tests
        working-directory: 'App'
        run: xcodebuild test -project TodoList.xcodeproj -scheme TodoList -destination 'platform=iOS Simulator,name=iPhone 13,OS=16.2'
