name: Swift

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "2.8-CI-CD-Artem" ]
    
jobs:
  build:
  
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Build
        working-directory: 'App/**'
        run: swift build -v
      - name: Run tests
        run: swift test -v
